In [39]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [40]:
train = pd.read_csv('train.csv', index_col='ID')
test = pd.read_csv('test.csv', index_col='ID')

In [41]:
train.head()

y = train["p50"]
X = train.drop(columns=["p50"])

In [42]:
X["ret_5d"] = X["p40"] / X["p35"] - 1
X["ret_10d"] = X["p40"] / X["p30"] - 1

In [43]:
returns = X.pct_change(axis=1)
returns = returns.drop(columns=["p1"])
returns.head()

,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,...,p33,p34,p35,p36,p37,p38,p39,p40,ret_5d,ret_10d
ID,,,,,,,,,,,,,,,,,,,,,
0,0.033424,0.042178,-0.029964,-0.032394,-0.032753,-0.046399,-0.049219,-0.014419,-0.005756,0.030877,...,-0.040742,-0.007021,-0.033036,-0.038000,-0.041121,-0.042365,-0.061609,-0.030080,-1.002922,0.077672
1,0.002305,-0.000287,0.002205,-0.012147,-0.041053,-0.026959,0.007264,-0.006078,-0.039075,-0.018121,...,0.075220,-0.011707,-0.009134,0.000288,-0.017423,0.002198,0.052785,-0.004583,-0.999550,0.725779
2,-0.000547,0.012229,-0.021547,-0.032710,-0.022290,0.044525,0.006996,0.058540,-0.023451,-0.001165,...,-0.002553,0.031914,0.015794,0.014165,0.015412,0.029012,0.012292,0.033771,-0.999200,0.178789
3,-0.014382,0.008407,0.002779,0.002485,-0.030219,-0.008257,0.039647,0.001239,0.004666,-0.000284,...,0.018948,0.000463,0.008877,-0.003850,0.026868,0.032527,0.015794,0.016830,-0.999236,0.103154
4,-0.056978,-0.027145,-0.018202,-0.038301,0.014193,0.006266,0.018163,0.007645,-0.039555,-0.032968,...,-0.032325,-0.013936,-0.019952,0.032976,0.035208,0.037283,0.041105,0.022037,-0.998381,-0.571565

In [44]:
X.head()

,p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,...,p33,p34,p35,p36,p37,p38,p39,p40,ret_5d,ret_10d
ID,,,,,,,,,,,,,,,,,,,,,
0,95.44,98.63,102.79,99.71,96.48,93.32,88.99,84.61,83.39,82.91,...,86.88,86.27,83.42,80.25,76.95,73.69,69.15,67.07,-0.195996,-0.211220
1,104.11,104.35,104.32,104.55,103.28,99.04,96.37,97.07,96.48,92.71,...,70.90,70.07,69.43,69.45,68.24,68.39,72.00,71.67,0.032263,0.055678
2,109.64,109.58,110.92,108.53,104.98,102.64,107.21,107.96,114.28,111.60,...,117.19,120.93,122.84,124.58,126.50,130.17,131.77,136.22,0.108922,0.128396
3,104.99,103.48,104.35,104.64,104.90,101.73,100.89,104.89,105.02,105.51,...,108.09,108.14,109.10,108.68,111.60,115.23,117.05,119.02,0.090926,0.100305
4,108.99,102.78,99.99,98.17,94.41,95.75,96.35,98.10,98.85,94.94,...,97.59,96.23,94.31,97.42,100.85,104.61,108.91,111.31,0.180257,0.077228